[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NPM_CONFIG_CACHE = "/opt/buildhome/.npm"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
